/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef master_CONSTANTS_H
#define master_CONSTANTS_H

#include "master_types.h"

namespace rpc { namespace master {

class masterConstants {
 public:
  masterConstants();

};

extern const masterConstants g_master_constants;

}} // namespace

#endif
