// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Master.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::rpc::master;

class MasterHandler : virtual public MasterIf {
 public:
  MasterHandler() {
    // Your initialization goes here
  }

  void Get(GetResponse& _return, const GetRequest& getRequest) {
    // Your implementation goes here
    printf("Get\n");
  }

  void Set(SetResponse& _return, const SetRequest& setRequest) {
    // Your implementation goes here
    printf("Set\n");
  }

  void Del(DelResponse& _return, const DelRequest& delRequest) {
    // Your implementation goes here
    printf("Del\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<MasterHandler> handler(new MasterHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new MasterProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

