/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "master_constants.h"

namespace rpc { namespace master {

const masterConstants g_master_constants;

masterConstants::masterConstants() {
}

}} // namespace

