/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef slave_CONSTANTS_H
#define slave_CONSTANTS_H

#include "slave_types.h"

namespace rpc { namespace slave {

class slaveConstants {
 public:
  slaveConstants();

};

extern const slaveConstants g_slave_constants;

}} // namespace

#endif
