/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "slave_constants.h"

namespace rpc { namespace slave {

const slaveConstants g_slave_constants;

slaveConstants::slaveConstants() {
}

}} // namespace

